### ISSUE TITLE
Cannot Use Passphrase to Unlock Miner Wallet

### ISSUE THREAD

**Issue by BlankerL** [touilleio/alephium-mining-companion#4]
Hi, I am a miner with a pre-generated mining address with a passphrase. 

Today, I was having a try on this mining companion, with `WALLET_NAME`, `WALLET_PASSWORD` and `WALLET_MNEMONIC_PASSPHRASE` set, but it keeps saying "Invalid mnemonic passphrase" even if I am sure my passphrase is correctly typed in. 

I went through the code, and found [the line](https://github.com/touilleio/alephium-mining-companion/blob/6b859f9ad62c34a11877c8a0f599f848a734623c/transfer_handler.go#L84) used to unlock the wallet is not using the passphrase if I understand it correctly.

I am a newbie to Golang and not able to fix the bug. Could you please have a check on this problem?

**Comment by killerwhile** [comment]
Thanks for reporting the issue. I'll check this.

**Comment by killerwhile** [comment]
The issue is confirmed, and is fixed in #7.
